name: BrandMeisterWidgetKit
options:
<<<<<<< HEAD
  bundleIdPrefix: com.osviel91
=======
  bundleIdPrefix: com.example
>>>>>>> 23a159dbfa4a4f5f48e3730b57792cc349883956
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    SWIFT_VERSION: 5.10
<<<<<<< HEAD
=======
    PRODUCT_NAME: BrandMeisterWidgetKit
>>>>>>> 23a159dbfa4a4f5f48e3730b57792cc349883956
    CODE_SIGN_STYLE: Automatic

targets:
  BrandMeisterMac:
    type: application
    platform: macOS
    sources:
      - path: MacApp
      - path: Shared
    info:
      path: MacApp/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
    entitlements:
      path: MacApp/BrandMeisterMac.entitlements
    settings:
      base:
<<<<<<< HEAD
        PRODUCT_NAME: BrandMeisterMac
        PRODUCT_BUNDLE_IDENTIFIER: com.osviel91.BrandMeisterMac
=======
        PRODUCT_BUNDLE_IDENTIFIER: com.example.BrandMeisterMac
>>>>>>> 23a159dbfa4a4f5f48e3730b57792cc349883956
    dependencies:
      - target: BrandMeisterWidgetExtension
        embed: true

  BrandMeisterWidgetExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: WidgetExtension
      - path: Shared
    info:
      path: WidgetExtension/Info.plist
    entitlements:
      path: WidgetExtension/BrandMeisterWidget.entitlements
    settings:
      base:
<<<<<<< HEAD
        PRODUCT_BUNDLE_IDENTIFIER: com.osviel91.BrandMeisterWidgetExtension
        PRODUCT_NAME: BrandMeisterWidgetExtension
=======
        PRODUCT_BUNDLE_IDENTIFIER: com.example.BrandMeisterWidgetExtension
        PRODUCT_NAME: BrandMeisterWidgetExtension
        INFOPLIST_KEY_NSExtensionPointIdentifier: com.apple.widgetkit-extension
        INFOPLIST_KEY_NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).BrandMeisterWidgetBundle"
>>>>>>> 23a159dbfa4a4f5f48e3730b57792cc349883956

schemes:
  BrandMeisterMac:
    build:
      targets:
        BrandMeisterMac: all
        BrandMeisterWidgetExtension: all
    run:
      config: Debug
